categorization_bazos = {
    "Auto": {
        "id": 2,
        "main_cat_items": {
            "Alfa Romeo": 9,
            "Audi": 5,
            "BMW": 6,
            "Citroën": 11,
            "Dacia": 13,
            "Fiat": 16,
            "Ford": 8,
            "Honda": 17,
            "Hyundai": 18,
            "Chevrolet": 10,
            "Kia": 21,
            "Mazda": 26,
            "Mercedes-Benz": 7,
            "Mitsubishi": 28,
            "Nissan": 29,
            "Opel": 30,
            "Peugeot": 31,
            "Renault": 33,
            "Seat": 36,
            "Suzuki": 39,
            "Škoda": 3,
            "Toyota": 41,
            "Volkswagen": 4,
            "Volvo": 43,
            "Ostatní značky": 44,
            "Autorádia": 51,
            "GPS navigace": 193,
            "Havarovaná auta": 49,
            "Náhradní díly": 46,
            "Pneumatiky, kola": 50,
            "Příslušenství": 46,
            "Tuning": 47,
            "Veteráni": 48,
            "Autobusy": 62,
            "Dodávky": 62,
            "Mikrobusy:": 62,
            "Karavany, vozíky": 62,
            "Nákladní auta": 62,
            "Pick-up": 62,
            "Ostatní užitková": 62,
            "Havarovaná": 62,
            "Náhradní díly užitková": 63,
        }
    },
    "Stroje": {
        "id": 64,
        "main_cat_items": {
            "Čerpadla": 45,
            "Čistící stroje": 134,
            "Dřevoobráběcí stroje": 135,
            "Generátory": 136,
            "Historické stroje": 137,
            "Kovoobráběcí stroje": 138,
            "Motory": 139,
            "Potravinářské stroje": 140,
            "Skladová technika": 141,
            "Stavební stroje": 142,
            "Textilní stroje": 143,
            "Tiskařské stroje": 144,
            "Vybavení provozoven": 145,
            "Výrobní linky": 146,
            "Zemědělská technika": 147,
            "Náhradní díly": 148,
            "Ostatní": 149,
        }
    },
    "Motorky": {
        "id": 52,
        "main_cat_items": {
            "Motorky": 52,
            "Cestovní motocykly": 53,
            "Čtyřkolky": 54,
            "Chopper": 53,
            "Enduro": 53,
            "Minibike": 53,
            "Mopedy": 59,
            "Silniční motocykly": 53,
            "Skútry": 55,
            "Skútry vodní": 55,
            "Skútry sněžné": 55,
            "Tříkolky": 53,
            "Veteráni": 57,
            "Náhradní díly": 58,
            "Oblečení, obuv, helmy": 59,
            "Ostatní": 60,
        }
    },
    "Děti": {
        "id": 67,
        "main_cat_items": {
            "Autosedačky": 68,
            "Baby monitory, chůvičky": 69,
            "Dětská literatura": 70,
            "Hračky": 71,
            "Lego": 71,
            "Hlídání dětí": 71,
            "Chodítka a hopsadla": 72,
            "Kočárky": 73,
            "Kojenecké potřeby": 74,
            "Kola": 76,
            "Nábytek pro děti": 75,
            "Nosítka": 72,
            "Odrážedla": 76,
            "Sedačky na kolo": 76,
            "Sportovní potřeby": 76,
            "Školní potřeby": 70,
            "Ostatní": 71,
            "Body, dupačky a overaly": 77,
            "Bundy a kabátky": 77,
            "Čepice a kloboučky": 77,
            "Kalhoty, kraťasy a tepláky": 77,
            "Kombinézy": 77,
            "Komplety": 77,
            "Mikiny a svetry": 77,
            "Obuv": 77,
            "Plavky": 77,
            "Ponožky a punčocháče": 77,
            "Pyžámka a župánky": 77,
            "Rukavice a šály": 77,
            "Spodní prádlo": 77,
            "Sukýnky a šatičky": 77,
            "Těhotenské oblečení": 77,
            "Trička a košile": 77,
            "Ostatní oblečení": 77,
        }
    },
    "Ostatní": {
        "id": 78,
        "main_cat_items": {
            "Mince, bankovky": 80,
            "Modelářství": 79,
            "Potraviny": 85,
            "Sběratelství": 80,
            "Sklo, keramika": 81,
            "Starožitnosti": 82,
            "Šperky, hodinky": 83,
            "Umělecké předměty": 84,
            "Zdraví a krása": 85,
            "Známky, pohledy": 80,
            "Ostatní": 85,
        }
    },
    "Hudba": {
        "id": 86,
        "main_cat_items": {
            "Bicí nástroje": 87,
            "Dechové nástroje": 87,
            "Klávesové nástroje": 87,
            "Smyčcové nástroje": 87,
            "Strunné nástroje": 87,
            "Ostatní nástroje": 91,
            "DVD, CD, MC, LP": 88,
            "Hudebníci a skupiny": 90,
            "Koncerty": 90,
            "Noty, texty": 91,
            "Světelná technika": 89,
            "Vstupenky": 92,
            "Výuka hudby": 91,
            "Zkušebny": 91,
            "Zvuková technika": 89,
            "Ostatní": 91
        }
    },
    "Vstupenky": {
        "id": 92,
        "main_cat_items": {
            "Dálniční známky": 92,
            "Dárkové poukazy": 92,
            "Jízdenky": 92,
            "Letenky": 92,
            "Permanentky": 92,
            "Divadlo": 92,
            "Festivaly": 92,
            "Hudba, Koncerty": 92,
            "Pro děti": 92,
            "Společenské akce": 92,
            "Sport": 92,
            "Výstavy": 92,
            "Ostatní": 92
        }
    },
    "Knihy": {
        "id": 93,
        "main_cat_items": {
            "Beletrie": 94,
            "Cizojazyčná literatura": 95,
            "Časopisy": 97,
            "Detektivky": 96,
            "Dětská literatura": 105,
            "Drama": 96,
            "Encyklopedie": 100,
            "Esoterika": 107,
            "Historické romány": 101,
            "Hobby, odborné knihy": 103,
            "Kuchařky": 102,
            "Mapy, cestovní průvodci": 99,
            "Počítačová literatura": 103,
            "Pro mládež": 198,
            "Romány pro ženy": 101,
            "Sci-fi, Fantasy": 106,
            "Učebnice, skripta - ZŠ": 104,
            "Učebnice, skripta - SŠ": 104,
            "Učebnice, skripta - VŠ": 104,
            "Učebnice, skripta - Jazykové": 104,
            "Zábavná": 198,
            "Zdravý životní styl": 102,
            "Ostatní": 107,
        }
    },
    "Dům a zahrada": {
        "id": 109,
        "main_cat_items": {
            "Bazény": 110,
            "Čerpadla": 45,
            "Dveře, vrata": 111,
            "Klimatizace": 112,
            "Kotle, Kamna, Bojlery": 112,
            "Malotraktory, Kultivátory": 147,
            "Míchačky": 114,
            "Nářadí": 114,
            "Okna": 111,
            "Pily": 147,
            "Radiátory": 112,
            "Rostliny": 113,
            "Sekačky": 116,
            "Sněžná technika": 116,
            "Stavební materiál": 114,
            "Vybavení dílen": 114,
            "Vysavače/Foukače": 115,
            "Zahradní grily": 116,
            "Zahradní nábytek": 131,
            "Zahradní technika": 116,
            "Ostatní": 117,
        }
    },
    "Nábytek": {
        "id": 118,
        "main_cat_items": {
            "Dětský nábytek": 75,
            "Dveře, vrata": 111,
            "Jídelní kouty": 122,
            "Knihovny": 129,
            "Koberce a podlah. krytina": 119,
            "Koupelny": 120,
            "Křesla a gauče": 121,
            "Kuchyně": 122,
            "Lampy, osvětlení": 123,
            "Ložnice": 124,
            "Matrace": 125,
            "Obývací stěny": 126,
            "Postele": 127,
            "Sedací soupravy": 128,
            "Skříně": 129,
            "Stoly": 130,
            "Zahradní nábytek": 131,
            "Židle": 130,
            "Doplňky": 132,
            "Ostatní nábytek": 133,
            }
        },
    "Elektro": {
        "id": 184,
        "main_cat_items": {
            "Digestoře": 248,
            "Ledničky": 242,
            "Mikrovlnné trouby": 243,
            "Mrazáky": 244,
            "Myčky": 245,
            "Pračky": 247,
            "Sporáky": 248,
            "Sušičky": 248,
            "Ostatní - bílá": 250,
            "Autorádia": 51,
            "Domácí kina": 188,
            "Fotoaparáty": 262,
            "GPS navigace": 193,
            "Hifi systémy, Rádia": 189,
            "Hudební nástroje": 86,
            "Projektory": 191,
            "Repro soustavy": 188,
            "Sluchátka": 192,
            "Televizory": 187,
            "Video, DVD přehrávače": 186,
            "Videokamery": 194,
            "Zesilovače": 190,
            "Ostatní audio video": 265,
            "Epilátory, Depilátory": 252,
            "Fény, Kulmy": 253,
            "Holící strojky": 254,
            "Kávovary": 246,
            "Nabíječky baterií": 255,
            "Ruční šlehače, Mixéry": 256,
            "Svítidla, Lampy": 257,
            "Šicí stroje": 258,
            "Vysavače": 261,
            "Vysílačky": 194,
            "Zvlhčovače vzduchu": 260,
            "Žehličky": 249,
            "Ostatní drobné": 194,
            }
        },
    "PC": {
        "id": 211,
        "main_cat_items": {
            "DVD, Blu-ray mechaniky": 217,
            "Fotoaparáty": 262,
            "GPS navigace": 193,
            "Grafické karty": 216,
            "Hard disky, SSD": 218,
            "Herní konzole": 214,
            "Herní zařízení": 227,
            "Hry": 237,
            "Chladiče": 219,
            "Klávesnice": 230,
            "Kopírovací stroje": 236,
            "LCD monitory": 232,
            "Mobilní telefony": 196,
            "Modemy": 233,
            "Myši": 230,
            "Notebooky": 213,
            "Paměti": 220,
            "PC, Počítače": 212,
            "Procesory": 221,
            "Síťové prvky": 224,
            "Scanery": 235,
            "Skříně, zdroje": 225,
            "Software": 238,
            "Spotřební materiál": 226,
            "Tablety, E-čtečky": 239,
            "Tiskárny": 234,
            "Wireless, WiFi": 228,
            "Základní desky": 222,
            "Záložní zdroje": 229,
            "Zvukové karty": 223,
            "Ostatní": 240,
            }
        },
    "Mobily": {
        "id": 196,
        "main_cat_items": {
            "Apple": 197,
            "HTC": 205,
            "Huawei, Honor": 200,
            "LG": 199,
            "Motorola, Lenovo": 202,
            "Nokia, Microsoft": 203,
            "Samsung": 198,
            "Sony": 204,
            "Xiaomi": 201,
            "Ostatní značky": 206,
            "Baterie": 208,
            "Bezdrátové telefony": 206,
            "Datové kabely": 208,
            "Faxy": 206,
            "GPS navigace": 193,
            "Headsety": 208,
            "HF Sady do auta": 208,
            "Chytré hodinky": 207,
            "Kryty": 208,
            "Nabíječky": 208,
            "Paměťové karty": 210,
            "Stolní telefony": 206,
            "Ostatní": 208,
            }
        },
    "Foto": {
        "id": 262,
        "main_cat_items": {
            "Analogové fotoaparáty": 263,
            "Digitální fotoaparáty": 263,
            "Drony": 264,
            "Videokamery": 265,
            "Zrcadlovky": 266,
            "Baterie": 267,
            "Blesky a osvětlení": 268,
            "Brašny a pouzdra": 267,
            "Datové kabely": 267,
            "Filtry": 267,
            "Nabíječky baterií": 267,
            "Objektivy": 269,
            "Paměťové karty": 267,
            "Stativy": 270,
            "Ostatní": 271,
            }
        },
    "Práce": {
        "id": 160,
        "main_cat_items": {
            "Administrativa": 161,
            "Chemie a potravinářství": 162,
            "Doprava a logistika": 163,
            "Finance a ekonomika": 164,
            "IT a telekomunikace": 165,
            "Marketing a reklama": 166,
            "Management": 167,
            "Obchod a prodej": 168,
            "Obrana a bezpečnost": 169,
            "Pohostinství a ubytování": 170,
            "Práce v domácnosti": 183,
            "Právo, legislativa": 171,
            "Průmysl a výroba": 172,
            "Řemeslné práce": 173,
            "Servis a služby": 174,
            "Stavebnictví": 175,
            "Technika a energetika": 176,
            "Tisk a polygrafie": 177,
            "Výzkum a vývoj": 178,
            "Vzdělávání a personalistika": 179,
            "Zdravotnictví": 180,
            "Zemědělství": 181,
            "Brigády": 182,
            "Ostatní": 183,
            }
        },
    "Reality": {
        "id": 150,
        "main_cat_items": {
            "Prodej": {
                "Byty": 151,
                "Domy": 152,
                "Nové projekty": 153,
                "Garáže": 153,
                "Hotely, penziony, restaurace": 155,
                "Chalupy, Chaty": 159,
                "Kanceláře": 154,
                "Obchodní prostory": 155,
                "Pozemky": 156,
                "Sklady": 157,
                "Zahrady": 158,
                "Ostatní": 159,
            },
            "Pronájem": {
                "Byty": 151,
                "Domy": 152,
                "Nové projekty": 159,
                "Podnájem, spolubydlící": 159,
                "Garáže": 153,
                "Hotely, penziony, restaurace": 155,
                "Ubytování": 159,
                "Kanceláře": 154,
                "Obchodní prostory": 155,
                "Pozemky": 156,
                "Sklady": 157,
                "Zahrady": 158,
                "Ostatní": 159,
            }
            }
        },
    "Oblečení": {
        "id": 272,
        "main_cat_items": {
            "Bundy a Kabáty": 273,
            "Čepice a Šátky": 274,
            "Džíny": 275,
            "Halenky": 286,
            "Kalhoty": 276,
            "Košile": 279,
            "Kožené oděvy": 277,
            "Mikiny": 278,
            "Obleky a Saka": 279,
            "Plavky": 280,
            "Rukavice a Šály": 290,
            "Spodní prádlo": 281,
            "Sportovní oblečení": 282,
            "Sukně": 283,
            "Svatební šaty": 284,
            "Svetry": 278,
            "Šaty, Kostýmky": 286,
            "Šortky": 276,
            "Těhotenské oblečení": 287,
            "Termo prádlo": 293,
            "Trička, Tílka": 288,
            "Batohy, Kufry": 292,
            "Boty": 289,
            "Doplňky": 290,
            "Hodinky": 291,
            "Kabelky": 292,
            "Šperky": 291,
            "Ostatní": 293,
                }
        },
    "Sport": {
        "id": 108,
        "main_cat_items": {
            "Fitness, jogging": 294,
            "Golf": 295,
            "Fotbal": 299,
            "In-lines, Skateboarding": 296,
            "Kempink": 297,
            "Letectví": 298,
            "Míčové hry": 299,
            "Myslivost, lov": 300,
            "Paintball": 301,
            "Rybaření": 302,
            "Společenské hry": 303,
            "Tenis, squash, badminton": 304,
            "Turistika, horolezectví": 305,
            "Vodní sporty, potápění": 306,
            "Vše ostatní": 307,
            "Dětská kola": 310,
            "Koloběžky": 309,
            "Horská kola": 310,
            "Silniční kola": 310,
            "Součástky a díly": 311,
            "Ostatní cyklistika": 312,
            "Běžkování": 315,
            "Lyžování": 315,
            "Skialpy": 316,
            "Snowboarding": 317,
            "Hokej, bruslení": 318,
            "Ostatní zimní": 319,
                }
        },
    "Služby": {
        "id": 346,
        "main_cat_items": {
            "Auto Moto": 328,
            "Cestování": 322,
            "Domácí práce": 323,
            "Esoterika": 324,
            "Hlídání dětí": 325,
            "IT, webdesign": 320,
            "Koně - služby": 326,
            "Kurzy a školení": 327,
            "Opravy, servis": 328,
            "Pořádání akcí": 329,
            "Právo a bezpečnost": 330,
            "Překladatelství": 331,
            "Přeprava a Stěhování": 332,
            "Půjčovny": 333,
            "Realitní služby": 334,
            "Reklama na auto": 335,
            "Reklamní plochy ostatní": 336,
            "Řemeslné a stavební práce": 321,
            "Služby pro zvířata": 337,
            "Tvůrčí služby": 338,
            "Ubytování": 339,
            "Účetnictví, poradenství": 340,
            "Úklid": 323,
            "Výroba": 341,
            "Výuka, doučování": 342,
            "Výuka hudby": 342,
            "Zdraví a krása": 343,
            "Zprostředkovatelské služby": 344,
            "Ostatní": 345,
                }
        },
    "Zvířata": {
        "id": 347,
        "main_cat_items": {
            "Akvarijní rybičky": 348,
            "Drobní savci": 349,
            "Kočky": 350,
            "Koně": 351,
            "Koně - potřeby": 351,
            "Koně - služby": 326,
            "Psi": 352,
            "Ptactvo": 353,
            "Terarijní zvířata": 354,
            "Ostatní domácí zvířata": 355,
            "Krytí": 356,
            "Ztraceni a nalezeni": 357,
            "Chovatelské potřeby": 358,
            "Služby pro zvířata": 337,
            "Drůbež": 359,
            "Králíci": 360,
            "Ovce a kozy": 361,
            "Prasata": 362,
            "Skot": 363,
            "Ostatní hospodářská zvířata": 364,
                }
        },
}
